#define MASS_L2 0.0
#define MASS_S2 0.0
#define Q2_MAX 25.0
#define MODEL 3
#define SUDAKOV 1
#define INDEPENDENT_RMAX 1
#define NONLINEAR 1
#define FEJER 1
#define N_CHEB_R 96
#define DGAUSS_PREC 1.0e-8
