#define MASS_L2 0.0
#define MASS_S2 0.0
#define Q2_MAX 650.0
#define MODEL 0 
#define PRINT_PROGRESS 1
#define ALPHA_RUN 1 
#define MODX 0
#define USE_RESULT 4
#define IBP 1
#define MU02 4
#define GLUON_APPROX 1
