all:	main.c\
	control.h\
	read-and-fit.h\
	dipole-cross-section.h\
	DIS-cross-section.h\
	photon-wave-function.h\
	constants.h\
	simpson-integral.h
	gcc main.c -o main -lm -lmathlib -lkernlib -lpacklib
