#define MASS_L2 0.0
#define MASS_S2 0.0
#define Q2_MAX 650.0
#define MODEL 0 
#define PRINT_PROGRESS 1
#define ALPHA_RUN 0
#define MODX 1 
#define USE_RESULT 0 
#define IBP 1
#define GLUON_APPROX 0
#define R_FORMULA 1
