#define MASS_L2 0.0
#define MASS_S2 0.0
#define Q2_MAX 650.0
#define MODEL 1 
#define GLUON_APPROX 1 
#define N_CHEB_R 200
#define PRINT_PROGRESS 1
#define ALPHA_RUN 0
#define MODX 0
#define IBP 2 
#define USE_RESULT 0 
#define SIGMA_APPROX -1
